project:
  type: website
  output-dir: docs
  twitter-card: 
    creator: "@steveondata"
    site: "@steveondata"
  site-url: https://www.spsanderson.com/steveondata/
  open-graph: true
  execute:
    freeze: auto

website:
  title: "Steve's Data Tips and Tricks"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spsanderson
      - icon: twitter
        href: https://twitter.com/steveondata/
      - icon: telegram
        href: https://t.me/steveondata
format:
  html:
    theme: 
      dark: darkly
    css: styles.css

editor: visual

