project:
  type: website
  output-dir: docs

website:
  twitter-card: 
    creator: "@steveondata"
    site: "@steveondata"
  site-url: https://www.spsanderson.com/steveondata/
  open-graph: true
  google-analytics: "G-JSJCM62KQJ"
  title: "Steve's Data Tips and Tricks"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spsanderson
      - icon: twitter
        href: https://twitter.com/steveondata/
      - icon: telegram
        href: https://t.me/steveondata
      - icon: rss
        href: http://feeds.feedburner.com/RBloggers
      - icon: rss
        href: index.xml
      - icon: book
        href: https://www.r-bloggers.com/
format:
  html:
    theme: 
      dark: darkly
    css: styles.css

editor: visual

